---

- hosts: all
  gather_facts: true
  roles:
    - geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - name: Copy config
      ansible.builtin.template:
        src: templates/.env
        dest: .env
        mode: 0644
    - name: Deploy redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports:
          - 80:3000
        state: started
        env_file: .env

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: true }
  vars:
    datadog_checks:
      process:
        init_config:
        instances:
          - name: Check website
            url: "https://home-cooking.ru/"
