---

- hosts: all
  gather_facts: yes
  roles:
    - geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - name: Copy config
      ansible.builtin.template:
        src: templates/.env
        dest: .env
      become: yes
    - name: Deploy redmine
      community.docker.docker_container:
        name: redmine
        image: redmine:{{ version }}
        ports:
          - 80:3000
        state: started
        env_file: ".env"

- hosts: webservers
  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/webservers/vault.yml
  roles:
      - { role: datadog.datadog, become: yes }
  vars:
    datadog_checks:
      process:
        init_config:
        instances:
          - name: Check website
            url: "{{ url }}"
